# @package _global_
defaults:
  - train_do_world
  - _self_

experiment: "do_world_causalworld"

model:
  env:
    suite: "causalworld"
    name: "pushing"
    image_size: [ 128, 128 ]
    max_episode_steps: 100
    action_repeat: 1

  counterfactual_mpc:
    robustness_weight: 0.7
